language: python
sudo: false 

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

addons:
  apt:
    packages:
      - libcpl-dev

install:
    - pip install coveralls
    - pip install astropy
    - python setup.py install

script: (cd test && coverage run --source=cpl TestRecipe.py && mv -f .coverage ..)

after_success: coveralls
