language: python
sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

addons:
  apt:
    packages:
      - libcpl-dev

install:
    - pip install coveralls
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install astropy==1.0.10; else pip install astropy; fi
    - python setup.py install

script: (cd test && coverage run --source=cpl TestRecipe.py && mv -f .coverage ..)

after_success: coveralls
